
export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD'; 

export const REQUEST_ALIENS_PENDING = 'REQUEST_ALIENS_PENDING';

export const REQUEST_ALIENS_SUCCESS = 'REQUEST_ALIENS_SUCCESS';

export const REQUEST_ALIENS_FAILED = 'REQUEST_ALIENS_FAILED';